site_name: Python SDK for Data Intelligence
site_description: 'Reference documentation for Python SDK for Data Intelligence solution provided by HPE storage'
site_author: Hewlett Packard Enterprise
theme:
  name: readthedocs
  custom_dir: hpe_theme/
  analytics:
    gtag: G-PC28RTKKTW
repo_name: hpe-storage/pydi-client
repo_url: https://github.com/hpe-storage/pydi-client
copyright: Copyright Hewlett Packard Enterprise Development LP
extra_css:
  - css/hpedev.css
nav:
  - Home: index.md
  - Concepts: concepts.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - API Reference:
      - Client: api/reference.md
      - Data Model: api/model.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            members_order: source
