name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:

  build:
    name: Build dists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: python -m pip install --upgrade pip poetry
      - name: Build package with Poetry
        run: poetry build
      - uses: actions/upload-artifact@v4
        with:
          name: dists
          path: dist/

  publish-pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    environment:
      name: pypi
      url: https://pypi.org/project/pydi-client/
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dists
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
          attestations: false
